logging:
  level:
    root: trace
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacodb
  cassandra:
    keyspace-name: taco_spring
    schema-action: recreate
    local-datacenter: datacenter1
server:
  shutdown: graceful