logging:
  level:
    root: trace
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacodb
server:
  shutdown: graceful
