logging:
  level:
    root: trace
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacodb
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - openid
              - email
              - profile

server:
  shutdown: graceful